"""empty message

Revision ID: 031dbedc6dfd
Revises: 91fa482ba2b4
Create Date: 2023-07-15 21:58:53.133497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '031dbedc6dfd'
down_revision = '91fa482ba2b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motor', schema=None) as batch_op:
        batch_op.alter_column('pinFunction',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('pinName',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motor', schema=None) as batch_op:
        batch_op.alter_column('pinName',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('pinFunction',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
