"""empty message

Revision ID: 2728f5058717
Revises: e0e2f0ee8eb4
Create Date: 2023-06-14 18:15:41.525928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2728f5058717'
down_revision = 'e0e2f0ee8eb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pinFunction', sa.String(length=200), nullable=False))
        batch_op.create_unique_constraint(None, ['pinFunction'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('motor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pinFunction')

    # ### end Alembic commands ###
