"""empty message

Revision ID: 4e05e429fe29
Revises: c8f4e24d6c9e
Create Date: 2023-10-18 12:01:50.136639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e05e429fe29'
down_revision = 'c8f4e24d6c9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklistedTokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('creationDate', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blacklistedTokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blacklistedTokens_jti'), ['jti'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blacklistedTokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blacklistedTokens_jti'))

    op.drop_table('blacklistedTokens')
    # ### end Alembic commands ###
