"""empty message

Revision ID: c8ca352dc35c
Revises: 6998c39941df
Create Date: 2023-06-19 20:44:41.269642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8ca352dc35c'
down_revision = '6998c39941df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('otp', sa.String(length=6), nullable=True))
    op.add_column('users', sa.Column('verifiedEmail', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verifiedEmail')
    op.drop_column('users', 'otp')
    # ### end Alembic commands ###
